### ISSUE TITLE
[transformers] command build:all fails

### ISSUE THREAD

**Issue by Oipo** [LandOfTheRair/Content#3]
Below is the command and output of the command build:all. 

npm version: 5.8.0
node version: 10.15.2
repo commit: 83f4e45c13a32eca8c134f1cd92a1a93c82b91b1 `move a boatload of shit to triggers`

```
oipo@oipo-X570-AORUS-ELITE:~/Programming/rair/Content$ npm run build:all
npm WARN npm npm does not support Node.js v10.15.2
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm Supported releases of Node.js are the latest release of 4, 6, 7, 8, 9.
npm WARN npm You can find the latest version at https://nodejs.org/

> content@0.0.0 build:all /home/oipo/Programming/rair/Content
> npm run build:items && npm run build:npcs && npm run build:droptables && npm run build:recipes && npm run build:lores && npm run build:spawners && npm run build:npc-scripts

npm WARN npm npm does not support Node.js v10.15.2
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm Supported releases of Node.js are the latest release of 4, 6, 7, 8, 9.
npm WARN npm You can find the latest version at https://nodejs.org/

> content@0.0.0 build:items /home/oipo/Programming/rair/Content
> node _transformers/item.js

TypeError: promises.flat is not a function
    at files.map.file (/home/oipo/Programming/rair/Content/_transformers/item.js:208:23)
    at Array.map (<anonymous>)
    at merge (/home/oipo/Programming/rair/Content/_transformers/item.js:184:26)
npm ERR! code ELIFECYCLE
npm ERR! errno 255
npm ERR! content@0.0.0 build:items: `node _transformers/item.js`
npm ERR! Exit status 255
npm ERR! 
npm ERR! Failed at the content@0.0.0 build:items script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/oipo/.npm/_logs/2019-10-02T20_00_22_521Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 255
npm ERR! content@0.0.0 build:all: `npm run build:items && npm run build:npcs && npm run build:droptables && npm run build:recipes && npm run build:lores && npm run build:spawners && npm run build:npc-scripts`
npm ERR! Exit status 255
npm ERR! 
npm ERR! Failed at the content@0.0.0 build:all script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/oipo/.npm/_logs/2019-10-02T20_00_22_535Z-debug.log
```

**Comment by seiyria** [comment]
Flat was introduced in nodejs 11. Can you get 11+? If my package.json
specifies 10 for some reason feel free to ignore that.

Kyle Kemp / Web Developer

920-215-1371/ kyle@seiyria.com


http://seiyria.com

**Comment by Oipo** [comment]
That was it, thanks.
